# Generated by Django 3.2.8 on 2021-10-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_liability', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
