# Generated by Django 3.2.8 on 2021-10-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zscore',
            name='year',
            field=models.IntegerField(),
        ),
    ]
